# Generated by Django 4.0.3 on 2022-09-04 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0003_alter_zwierze_options_zwierze_breed_zwierze_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animaltype',
            options={'verbose_name': 'Gatunek', 'verbose_name_plural': 'Gatunki'},
        ),
        migrations.AlterModelOptions(
            name='sex',
            options={'verbose_name': 'Płeć', 'verbose_name_plural': 'Płcie'},
        ),
        migrations.AlterField(
            model_name='zwierze',
            name='last_visit',
            field=models.DateField(null=True, verbose_name='Ostatnia wizyta'),
        ),
    ]
