# Generated by Django 4.0.3 on 2022-09-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0004_alter_animaltype_options_alter_sex_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwierze',
            name='phone_number',
            field=models.IntegerField(max_length=20, null=True, verbose_name='Numer tel.'),
        ),
    ]
