# Generated by Django 4.0.3 on 2022-09-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0005_alter_zwierze_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwierze',
            name='phone_number',
            field=models.CharField(max_length=9, null=True, verbose_name='Numer tel.'),
        ),
    ]
