# Generated by Django 4.0.3 on 2022-09-04 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0008_alter_zwierze_year_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwierze',
            name='breed',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Rasa'),
        ),
    ]
