# Generated by Django 4.0.3 on 2022-09-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0010_alter_zwierze_year_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zwierze',
            name='slug',
        ),
    ]
