# Generated by Django 4.0.3 on 2022-09-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0011_remove_zwierze_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zwierze',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data dodania'),
        ),
    ]
