# Generated by Django 4.0.3 on 2022-09-07 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('klienci', '0013_wizyty'),
    ]

    operations = [
        migrations.AddField(
            model_name='wizyty',
            name='create_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Data dodania'),
        ),
        migrations.AddField(
            model_name='wizyty',
            name='visit_time',
            field=models.TimeField(null=True, verbose_name='Godzina wizyty'),
        ),
        migrations.AlterField(
            model_name='wizyty',
            name='visit_date',
            field=models.DateField(verbose_name='Data wizyty'),
        ),
    ]
